services:
  rw-tg-mini-app:
    image: ghcr.io/legiz-ru/rw-tg-mini-app:latest
    container_name: rw-tg-mini-app
    hostname: rw-tg-mini-app
    restart: always
    volumes:
      # Mount protected assets config
      - ./app-config.json:/app/public/assets-protected/app-config.json
      # Optional: mount custom pages or assets
      # - ./custom-pages:/app/src/app/custom
    env_file:
      - .env-mini-app
    ports:
      - '127.0.0.1:3000:3000' # Changed from 3020 to 3000 for Next.js
    networks:
      - remnawave-network

networks:
  remnawave-network:
    driver: bridge
    external: true